# Generated by Django 5.2.11 on 2026-03-17 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('followed', models.ForeignKey(db_column='followed_id', on_delete=django.db.models.deletion.CASCADE, related_name='follower_relations', to=settings.AUTH_USER_MODEL)),
                ('follower', models.ForeignKey(db_column='follower_id', on_delete=django.db.models.deletion.CASCADE, related_name='following_relations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'follows',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['follower'], name='follows_followe_ca9b09_idx'), models.Index(fields=['followed'], name='follows_followe_a0ecff_idx')],
                'constraints': [models.UniqueConstraint(fields=('follower', 'followed'), name='unique_follow_relation'), models.CheckConstraint(condition=models.Q(('follower', models.F('followed')), _negated=True), name='follows_not_self')],
            },
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('friend', models.ForeignKey(db_column='friend_id', on_delete=django.db.models.deletion.CASCADE, related_name='friend_requests_received', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='friend_requests_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'friends',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='friends_user_id_71f36d_idx'), models.Index(fields=['friend', 'status'], name='friends_friend__1f35fd_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'friend'), name='unique_friend_request'), models.CheckConstraint(condition=models.Q(('user', models.F('friend')), _negated=True), name='friends_not_self')],
            },
        ),
    ]
